name: PR Label Check

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

permissions:
  pull-requests: read

jobs:
  label-check:
    name: Validate PR Labels
    runs-on: ubuntu-latest
    steps:
      - name: Check required labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "bug, enhancement, documentation, devops"
          message: "Please add at least one label to categorize this PR (bug, enhancement, documentation, or devops)"
